let num1 = prompt('Введите первое число');
let num2 = prompt('Введите второе число');
let result = num1 * num2;
let result1 = num1 / num2;
let result2 = +num1 + +num2;
let result3 = num1 - num2;
alert(result,result1,result2,result3);
console.log(`Результат:${num1}*${num2}=${result}`);
console.log(`Результат:${num1}/${num2}=${result1}`);
console.log(`Результат:${num1}+${num2}=${result2}`);
console.log(`Результат:${num1}-${num2}=${result3}`);